version: '3.7'

services:
  www:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ".:/var/www/:ro"
      - ".docker.nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8888:80"
  php:
    image: juitde/php:7.4.9
    restart: always
    environment:
      PHP_EXTENSIONS: "opcache intl"
    working_dir: "/var/www/"
    volumes:
      - ".:/var/www/:cached"

  encore:
    image: node:12.14.1-alpine
    restart: always
    volumes:
      - ".:/app"
    working_dir: /app
    command: >
      sh -c "npm install && npm run-script dev-server -- --keep-public-path --host=0.0.0.0 --port=8888 --disableHostCheck"
